'use strict';

import keyMirror from 'react/lib/keyMirror';

export default keyMirror({

  REG_SUBMIT: null,
  REG_SUCCESS: null,
  REG_FAILURE: null,
  REFRESH_REGV: null,
  LOGIN_SUBMIT: null,
  LOGIN_SUCCESS: null,
  LOGIN_FAILURE: null,
  LOGOUT_SUBMIT: null,
  REFRESH_LOGINV: null,


  SELL_ORDERS_KEY: null,
  SELL_ORDERS_KEY_FAILURE: null,
  SELL_ORDERS_NULL: null,
  SELL_ORDERS_FAILURE: null,
  SELL_ORDERS_SUCCESS: null,


  APPLY_SELL_SUBMIT: null,
  APPLY_SELL_SUCCESS: null,
  APPLY_SELL_FAILURE: null,
  APPLY_SELL_NEW: null,
  SELL_NEW_ITEM:null,
  SELL_CHANGE_DATA: null,
  SELL_REMOVE_ITEM: null,

  APPLY_SELL_SUBMIT_C2C: null,
  APPLY_SELL_SUCCESS_C2C: null,
  APPLY_SELL_FAILURE_C2C: null,
  APPLY_SELL_NEW_C2C: null,
  SELL_NEW_ITEM_C2C:null,
  SELL_CHANGE_DATA_C2C: null,
  SELL_CHANGE_IMAGE_C2C: null,
  SELL_REMOVE_ITEM_C2C: null,

  ADD_TO_SUBMIT: null,
  REMOVE_FROM_SUBMIT:null,

  CHANGE_INFO_SUBMIT: null,
  CHANGE_INFO_SUCCESS: null,
  CHANGE_INFO_FAILURE: null,

  FIND_PASSWORD_SUBMIT: null,
  FIND_PASSWORD_SUCCESS: null,
  FIND_PASSWORD_FAILURE: null,

  UPLOAD_AVATAR_START:null,
  UPLOAD_AVATAR_END:null,
  UPLOAD_AVATAR_SUBMIT: null,
  UPLOAD_AVATAR_SUCCESS: null,
  UPLOAD_AVATAR_FAILURE: null,

  C2C_SUCCESS_CLICK:null

});
